// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrjnO7l9JPNm9qNow3iGi1ufjZWpvHlE',
    appId: '1:243427015309:web:a5beb016239baff58940c4',
    messagingSenderId: '243427015309',
    projectId: 'objetos-perdidos-upt',
    authDomain: 'objetos-perdidos-upt.firebaseapp.com',
    storageBucket: 'objetos-perdidos-upt.firebasestorage.app',
    measurementId: 'G-J6507EJ99W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMp9kX8Mi23R1u75X0gWZfoxH74ePhTU0',
    appId: '1:243427015309:android:b883a0275901d2bf8940c4',
    messagingSenderId: '243427015309',
    projectId: 'objetos-perdidos-upt',
    storageBucket: 'objetos-perdidos-upt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3qj7EhLVZlj-szYD7IkAzfPxEE3FIFo',
    appId: '1:243427015309:ios:3daa8d3c263f7cc38940c4',
    messagingSenderId: '243427015309',
    projectId: 'objetos-perdidos-upt',
    storageBucket: 'objetos-perdidos-upt.firebasestorage.app',
    iosBundleId: 'com.example.objetosPerdidosUpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3qj7EhLVZlj-szYD7IkAzfPxEE3FIFo',
    appId: '1:243427015309:ios:3daa8d3c263f7cc38940c4',
    messagingSenderId: '243427015309',
    projectId: 'objetos-perdidos-upt',
    storageBucket: 'objetos-perdidos-upt.firebasestorage.app',
    iosBundleId: 'com.example.objetosPerdidosUpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIrjnO7l9JPNm9qNow3iGi1ufjZWpvHlE',
    appId: '1:243427015309:web:41f6555bd5adffcc8940c4',
    messagingSenderId: '243427015309',
    projectId: 'objetos-perdidos-upt',
    authDomain: 'objetos-perdidos-upt.firebaseapp.com',
    storageBucket: 'objetos-perdidos-upt.firebasestorage.app',
    measurementId: 'G-XMYPPSH00J',
  );
}
